# Generated by Django 3.0.4 on 2020-04-04 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='agencias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codAgencia', models.CharField(max_length=8)),
                ('nombre', models.CharField(max_length=20)),
                ('direccion', models.CharField(blank=True, default='', max_length=30)),
                ('cp', models.CharField(default='', max_length=5)),
                ('telefono', models.CharField(blank=True, default='', max_length=9)),
                ('movil', models.CharField(blank=True, default='', max_length=9)),
                ('mail', models.EmailField(max_length=254, null=True)),
            ],
        ),
    ]
