# Generated by Django 3.0.4 on 2020-04-04 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencias', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agencias',
            name='cp',
            field=models.CharField(blank=True, default='', max_length=5),
        ),
        migrations.AlterField(
            model_name='agencias',
            name='direccion',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='agencias',
            name='mail',
            field=models.EmailField(blank=True, default='', max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='agencias',
            name='nombre',
            field=models.CharField(max_length=40),
        ),
    ]
