# Generated by Django 3.0.4 on 2020-03-29 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='familia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=25)),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='articulos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=8)),
                ('nombre', models.CharField(max_length=70)),
                ('fabricante', models.CharField(max_length=20)),
                ('proveedor', models.CharField(max_length=20, null=True)),
                ('codbarras', models.CharField(max_length=50, null=True)),
                ('codqr', models.CharField(max_length=255, null=True)),
                ('precio', models.FloatField(default=0)),
                ('familia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articulos.familia')),
            ],
            options={
                'unique_together': {('codigo', 'fabricante')},
            },
        ),
    ]
