# Generated by Django 3.0.4 on 2020-04-01 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulos',
            name='imagen',
            field=models.ImageField(default='', max_length=50, upload_to=''),
        ),
        migrations.AlterField(
            model_name='articulos',
            name='codbarras',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='articulos',
            name='codqr',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='familia',
            name='codigo',
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
