# Generated by Django 3.0.4 on 2020-04-01 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0002_auto_20200401_2340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulos',
            name='codbarras',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='articulos',
            name='codqr',
            field=models.CharField(default='', max_length=255),
        ),
    ]
