# Generated by Django 3.0.4 on 2020-04-04 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0002_auto_20200404_2114'),
        ('articulos', '0003_auto_20200401_2340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulos',
            name='proveedor',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='proveedores.proveedores'),
            preserve_default=False,
        ),
    ]
