# Generated by Django 3.0.4 on 2020-04-04 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0005_auto_20200404_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulos',
            name='codbarras',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='articulos',
            name='codqr',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
