# Generated by Django 3.0.4 on 2020-04-05 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('articulos', '0006_auto_20200404_2243'),
        ('proveedores', '0003_auto_20200404_2206'),
    ]

    operations = [
        migrations.CreateModel(
            name='ubicacionesStocks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sala', models.CharField(max_length=10)),
                ('modulo', models.CharField(max_length=6)),
                ('estanteria', models.CharField(max_length=6)),
                ('ubicacion', models.CharField(max_length=6)),
                ('stock', models.FloatField()),
                ('fk_articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articulos.articulos')),
                ('fk_proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proveedores.proveedores')),
            ],
        ),
    ]
