# Generated by Django 3.0.4 on 2020-03-29 18:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='salidas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=8)),
                ('fechaSalida', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('unidades', models.IntegerField()),
                ('precioUnidad', models.FloatField()),
                ('agencia', models.CharField(max_length=20, null=True)),
                ('precioPorte', models.FloatField(null=True)),
                ('enviado', models.BooleanField()),
            ],
        ),
    ]
