# Generated by Django 3.0.4 on 2020-04-01 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0002_auto_20200401_2340'),
        ('entradas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entradas',
            name='fk_articulo',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='articulos.articulos'),
        ),
        migrations.AddField(
            model_name='entradas',
            name='nombre',
            field=models.CharField(max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='entradas',
            name='codigo',
            field=models.CharField(max_length=8, verbose_name='codigo'),
        ),
    ]
