# Generated by Django 3.0.4 on 2020-04-03 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_auto_20200403_2059'),
        ('entradas', '0004_auto_20200402_0000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entradas',
            name='fk_articulo',
        ),
        migrations.RemoveField(
            model_name='entradas',
            name='nombre',
        ),
        migrations.AddField(
            model_name='entradas',
            name='fk_cliente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='clientes.clientes'),
        ),
        migrations.AddField(
            model_name='entradas',
            name='peso',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='entradas',
            name='porte_pagado',
            field=models.NullBooleanField(default=False),
        ),
    ]
