# Generated by Django 3.0.5 on 2020-04-02 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entradas', '0004_auto_20200402_0000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entradas',
            name='fk_articulo',
        ),
    ]
