# Generated by Django 3.0.5 on 2020-04-02 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0003_auto_20200401_2340'),
        ('entradas', '0005_remove_entradas_fk_articulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='entradas',
            name='fk_articulo',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='articulos.articulos'),
        ),
    ]
