# Generated by Django 3.0.4 on 2020-04-03 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entradas', '0005_auto_20200403_2059'),
    ]

    operations = [
        migrations.AddField(
            model_name='entradas',
            name='precioTotal',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
