# Generated by Django 3.0.5 on 2020-04-02 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0003_auto_20200401_2340'),
        ('entradas', '0006_entradas_fk_articulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entradas',
            name='agencia',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='entradas',
            name='fk_articulo',
            field=models.ForeignKey(blank=True, default=2, on_delete=django.db.models.deletion.CASCADE, to='articulos.articulos'),
        ),
        migrations.AlterField(
            model_name='entradas',
            name='nombre',
            field=models.CharField(blank=True, max_length=70),
        ),
        migrations.AlterField(
            model_name='entradas',
            name='precioPorte',
            field=models.FloatField(blank=True),
        ),
    ]
