# Generated by Django 3.0.4 on 2020-04-03 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entradas', '0006_entradas_preciototal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entradas',
            name='precioTotal',
            field=models.FloatField(default=0),
        ),
    ]
