# Generated by Django 3.0.4 on 2020-04-03 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entradas', '0007_auto_20200403_2134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entradas',
            name='precioTotal',
        ),
    ]
