# Generated by Django 3.0.4 on 2020-04-03 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entradas', '0008_remove_entradas_preciototal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entradas',
            name='agencia',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='entradas',
            name='precioPorte',
            field=models.FloatField(),
        ),
    ]
