# Generated by Django 3.0.4 on 2020-04-03 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entradas', '0010_auto_20200403_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entradas',
            name='agencia',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='entradas',
            name='precioPorte',
            field=models.FloatField(blank=True, default=True, null=True),
        ),
    ]
