# Generated by Django 3.0.4 on 2020-04-04 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0005_auto_20200404_2114'),
        ('proveedores', '0002_auto_20200404_2114'),
        ('agencias', '0001_initial'),
        ('entradas', '0012_auto_20200403_2341'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entradas',
            name='codigo',
        ),
        migrations.AddField(
            model_name='entradas',
            name='fk_proveedor',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='proveedores.proveedores'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entradas',
            name='nAlbaran',
            field=models.CharField(default='', max_length=8, verbose_name='Albaran'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='entradas',
            name='agencia',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='agencias.agencias'),
        ),
        migrations.AlterField(
            model_name='entradas',
            name='fk_cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.clientes'),
        ),
        migrations.AlterField(
            model_name='entradas',
            name='precioPorte',
            field=models.FloatField(blank=True, default=True),
        ),
    ]
