# Generated by Django 3.0.4 on 2020-04-04 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0005_auto_20200404_2206'),
        ('entradas', '0013_auto_20200404_2114'),
    ]

    operations = [
        migrations.AddField(
            model_name='entradas',
            name='fk_articulo',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='articulos.articulos'),
            preserve_default=False,
        ),
    ]
