# Generated by Django 3.0.4 on 2020-04-04 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entradas', '0014_entradas_fk_articulo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entradas',
            name='fk_cliente',
        ),
    ]
