# Generated by Django 3.0.4 on 2020-04-06 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entradas', '0015_remove_entradas_fk_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entradas',
            name='fk_articulo',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AlterField(
            model_name='entradas',
            name='porte_pagado',
            field=models.BooleanField(default=True),
        ),
    ]
