# Generated by Django 3.0.4 on 2020-04-08 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0006_auto_20200404_2243'),
        ('entradas', '0016_auto_20200406_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entradas',
            name='fk_articulo',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='articulos.articulos'),
        ),
    ]
