# Generated by Django 3.0.4 on 2020-04-03 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientes',
            old_name='nombre',
            new_name='cliente',
        ),
        migrations.RemoveField(
            model_name='clientes',
            name='activo',
        ),
    ]
