# Generated by Django 3.0.4 on 2020-04-03 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_auto_20200403_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
