# Generated by Django 3.0.4 on 2020-04-04 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_auto_20200403_2300'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientes',
            old_name='codigo',
            new_name='codigoCliente',
        ),
        migrations.RenameField(
            model_name='clientes',
            old_name='cliente',
            new_name='nombreCliente',
        ),
    ]
