# Generated by Django 3.0.4 on 2020-03-29 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='proveedores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=8)),
                ('nombre', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=50, null=True)),
                ('cp', models.CharField(max_length=5, null=True)),
                ('telefono', models.CharField(max_length=9, null=True)),
                ('movil', models.CharField(max_length=9, null=True)),
            ],
        ),
    ]
