# Generated by Django 3.0.4 on 2020-04-04 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proveedores',
            old_name='codigo',
            new_name='codProveedor',
        ),
        migrations.AddField(
            model_name='proveedores',
            name='mail',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
